server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:viajes;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_UPPER=false
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: none         # usamos schema.sql/data.sql, no autogenerar
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always           # ejecuta schema.sql y data.sql al arrancar
  h2:
    console:
      enabled: true
      path: /h2

# Orígenes permitidos para tu front local (cámbialos si procede)
app:
  cors:
    allowed-origins: "http://localhost:5173,http://localhost:3000"
