drop table if exists cliente;
drop table if exists evento;

create table cliente (
  id bigint generated by default as identity primary key,
  nombre varchar(100) not null,
  apellidos varchar(150) not null,
  username varchar(60) not null unique,
  correo varchar(180) not null unique,
  fecha_nacimiento date not null,
  ciudad varchar(120),
  idioma varchar(20),
  password_hash varchar(100) not null
);

create table evento (
  id bigint generated by default as identity primary key,
  fecha date not null,
  hora time not null,
  lugar varchar(200) not null,
  idiomas_permitidos varchar(200),
  edad_minima integer,
  max_personas integer,
  titulo varchar(200) not null,
  descripcion clob
);
